### ISSUE TITLE
Tests fail without mutations for file

### ISSUE THREAD

**Issue by blabno** [jimivdw/grunt-mutation-testing#62]
When I run tests normally, they all pass.
When I comment out some tests then mutation works fine, but when I uncomment some tests then I get

```
(16:32:03.783) INFO [KarmaServerManager]: Karma server started after 3100ms and is listening on port 12111
[2016-05-27 16:32:03.894] [DEBUG] config - Loading config /home/project/test/karma.conf.js
(16:32:05.896) WARN [mutation-testing-karma]: Warning! Infinite loop detected. This may put a strain on your CPU.
(16:32:05.896) ERROR [mutation-testing-karma]: Fatal: Unfortunately the mutation test cannot recover from this error and will shut down
(16:32:05.898) WARN [mutation-testing]: Tests fail without mutations for file: /tmp/mutation-testing116427-5613-p3fcyj/activeArtifact.controller.js
(16:32:05.899) WARN [mutation-testing]: This failure may be due to a misconfiguration of either `code` or `specs`. Did you include your external libraries?
```

**Comment by simondel** [comment]
Hey! :)

1. Do you use Mocha or Jasmine?
2. Is your project open source?

**Comment by blabno** [comment]
1. Karma + mocha + chai
2. No

**Comment by blabno** [comment]
Is there any chance to see failing test report?

**Comment by simondel** [comment]
I unfortunately have no idea. I was hoping you would have an open source project with Jasmine so I could run it with [Stryker](https://github.com/stryker-mutator/stryker), which unfortunately does not yet support Mocha (we're [working on it](https://github.com/stryker-mutator/stryker/tree/mocha-support) though).

**Comment by blabno** [comment]
Well, best luck on mocha support. Really looking forward to being able to verify mocha coverage.

**Comment by blabno** [comment]
hm. I've just spotted that if I modify `waitForRunnerTime` and set it to some high value, then everything works well.
