### ISSUE TITLE
arithmetic mutation breaks code syntax

### ISSUE THREAD

**Issue by paysdoc** [jimivdw/grunt-mutation-testing#7]
Arithmetic mutation (and probably also comparison expression) breaks the syntax of the mutated code.
Consider :
```javascript 
var answer = 6 + (7 + 31);
```
The relevant syntax tree fragment looks like this:
`
{  
   "range": [13,25],
   "type":"BinaryExpression",
   "operator":"+",
   "left":{  
      "range":[13,14],
      "type":"Literal",
      "value":6,
      "raw":"6"
   },
   "right":{  
      "range":[18,2],
      "type":"BinaryExpression",
      "operator":"+",
      "left":{  
         "range":[18,19],
         "type":"Literal",
         "value":7,
         "raw":"7"
      },
      "right":{  
         "range":[22,24],
         "type":"Literal",
         "value":31,
         "raw":"31"
      }
   }
}
`
Evidently 'left' ends at range index 14 and 'right' starts at range index 18. That leaves 14(which is the space *after* 14),15,16 and 17, or `' + ('`
The resulting mutation (after replacing `+` by `-`) is: 
```javascript
var answer = 6-7 + 31);
```

There are some workarounds. But the only real solution to me seems to me to do the mutation in the AST and (using codegen) serialise that.

**Comment by jimivdw** [comment]
@paysdoc was this fixed completely in your reporting branch?

**Comment by paysdoc** [comment]
I did implement a workaround which solved the problem but I still think that we should drop the two-step mutation. Did you discover any more problems?
